# Generated by Django 3.2.9 on 2021-11-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_category',
            field=models.CharField(choices=[(1, 'Vegitarian'), (2, 'Chinese'), (3, 'Meal'), (4, 'Icecreams'), (5, 'Shakes'), (6, 'Soups')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='food_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
