# Generated by Django 3.2.9 on 2021-11-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20211111_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_category',
            field=models.CharField(choices=[('VEGITARIAN', 'Vegitarian'), ('CHINESE', 'Chinese'), ('MEAL', 'Meal'), ('ICECREAMS', 'Icecreams'), ('SHAKES', 'Shakes'), ('SOUPS', 'Soups')], max_length=100),
        ),
    ]
